[package]
name = "rust-gamedev-tutorial"
version = "0.1.0"
authors = ["Oleksandr Kovalchuk <a.kovalchuk@smartweb.com.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "= 0.34.5"
